### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/detic_ros#2]
## major 
- [x] publish pcl_msgs/pointInices
- [x] publish/subscribe compressed image 
- [ ] publish image bounding box 
- [ ] fix up docker file (especially part where torch installation procedure)
## minor
- [x] check installation instruction in README.md
- [x] use user-defined instance class names

**Comment by 708yamaguchi** [comment]
Use docker for melodic.

rosdep command is wrong. Use `--from-paths`

Do we need to install `pip3 install opencv-python`?

In `prepare.sh`, should shebang `/bin/bash`?

**Comment by HiroIshida** [comment]
prepare_docker branch
```
docker build -t detic_ros .
docker run --rm --net=host -it --gpus 1 detic_ros:latest /bin/bash -i -c 'source ~/.bashrc; rossetip; rossetmaster pr1040; roslaunch detic_ros sample.launch'
```
